### ISSUE TITLE
Bug with registration

### ISSUE THREAD

**Issue by egorgam** [wichmannpas/django-rest-authtoken#1]
remove REGISTRATION_EMAIL_CONFIRM in:

https://github.com/wichmannpas/django-rest-authtoken/blob/master/rest_authtoken/urls.py#L21

because there is no way to use a library with REGISTRATION_EMAIL_CONFIRM=False and REGISTRATION_ENABLED=True, it's a bug.

**Comment by wichmannpas** [comment]
Thanks for reporting an issue!
What exactly is the problem that you are reporting?
The email confirmation is an optional feature. django-rest-authtoken is usable with enabled registration (`REGISTRATION_ENABLED=True`) but without email confirmation (`REGISTRATION_EMAIL_CONFIRM=False`).
In this case, no email is sent, not allowing to set a specified model attribute to `True` upon confirmation

**Comment by wichmannpas** [comment]
Thanks for reporting this issue!
The problem is that a confirmation email is currently attempted to be sent even if that feature is disabled. I will fix this.
